
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS sex;
DROP TABLE IF EXISTS curr;
DROP TABLE IF EXISTS loct;
DROP TABLE IF EXISTS city;
DROP TABLE IF EXISTS prov;
DROP TABLE IF EXISTS regn;
DROP TABLE IF EXISTS nats;
DROP TABLE IF EXISTS cont;
